# Generated by Django 5.0.6 on 2024-05-20 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_pricingplan_pricing_alter_pricingplan_plans'),
        ('payments', '0003_alter_payment_id_alter_userwallet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.pricingplan'),
        ),
    ]
