# Generated by Django 5.0.6 on 2024-05-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
